### Numpy (Numerical Python) Library

In [ ]:
# NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data
# structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python. 
# NumPy contains, among other things:

# ● A fast and efficient multidimensional array object ndarray
# ● Functions for performing element-wise computations with arrays or mathematical
# operations between arrays
# ● Tools for reading and writing array-based datasets to disk
# ● Linear algebra operations, Fourier transform, and random number generation
# ● A mature C API to enable Python extensions and native C or C++ code to access

In [ ]:
# NumPy’s data structures and computational facilities.

# Beyond the fast array-processing capabilities that NumPy adds to Python, one of its primary uses in data analysis is as a
# container for data to be passed between algorithms and libraries.

# For numerical data, NumPy arrays are more efficient for storing and manipulating data than the other built-in Python
# data structures. Also, libraries written in a lower-level language, such as C or Fortran, can operate on the data stored
# in a NumPy array without copying data into some other memory representation. Thus, many numerical computing tools for
# Python either assume NumPy arrays as a primary data structure or else target seamless interoperability with NumPy.

In [ ]:
# Why Numpy?
# One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on
# large arrays of data. There are a number of reasons for this:
# ● NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s
# library of algorithms written in the C language can operate on this memory without any type checking or other overhead. 
# NumPy arrays also use much less memory than built-in Python sequences.
# ● NumPy operations perform complex computations on entire arrays without the need for Python for loops. To give you an
# idea of the performance difference, consider a NumPy array of one million integers, and the equivalent Python list:

In [ ]:
import numpy as np

nump_a = np.arange(10000000)
list_a = list(range(10000000))

print(len(nump_a))

print(len(list_a))

In [ ]:
%%time

nump_a2 = nump_a * 2

In [ ]:
%%time
list_a2 = [x*2 for x in list_a]

In [ ]:
nump_b = np.arange(10)
list_b = list(range(10))

nump_m = nump_b * 2

In [ ]:
list_c = list_b*2

In [ ]:
list_d = [x*2 for x in list_b]

print(nump_m, type(nump_m))
print(list_c, type(list_c))
print(list_d, type(list_d))

In [ ]:
# The NumPy ndarray
# A Multidimensional Array Object One of the key features of NumPy is its N-dimensional array object, or ndarray, which is
# a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole
# blocks of data using similar syntax to the equivalent operations between scalar elements.

In [ ]:
print(dir(np))

In [ ]:
data = np.random.randint(1,10,24).reshape(2,3,4)

print(data)

In [ ]:
data1 = np.random.randint(1,10,24)

print(data1)

In [ ]:
data2 = np.random.randint(1,10,24).reshape(4,6)
print(data2)

In [ ]:
# Note the appearance is of a 3 layer nested list. However, though they appear the same - these are arrays!! Important :
# note NO commas between the elements of the array. 

print(type(data))

for x in range(len(data)):
    for y in range(len(data[x])):
        for z in range(len(data[x][y])):
            print(data[x][y][z])
            
# The 3 dimensional array object is constructed of : 4 elements in each row, 3 rows nested in the 2nd dimension of the 
# array object and 2 such 2nd Dimension arrays nested in the outer most array block. 

In [ ]:
print(data)

In [ ]:
print(data * 10)

In [ ]:
# Note, we have not changed the original data ndarray.
print(data)

# We could change the original data variable by assigning the result to itself or to a new variable as usual.

In [ ]:
print(data+data)

In [ ]:
data1 = data*10

print(data1)

In [ ]:
data1 = data1+data1
print(data1)

In [ ]:
# An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same
# type. 

lst1 = ['a', 100, (20,30), {'x':10, 'y':20}]

np_arr = np.array(lst1)

In [ ]:
print(np_arr)
print(np_arr.dtype)

print(type(np_arr[2]))

In [ ]:
np_arr = np.array(lst1, dtype = int)

In [ ]:
# Unless explicitly specified, np.array tries to infer a good data type for the array that it creates.

In [ ]:
lst2 = [2.0, 300, 72, 3.4, 5.78]

np_arr = np.array(lst2)

In [ ]:
lstalpha = [1,2,3,4]

print(lstalpha)

In [ ]:
np_str = np.array(lstalpha, dtype = str)

print(np_str)
print(type(np_str[0]))
print(type(np_str))

In [ ]:
print(np_arr)
print(np_arr.dtype)


for x in np_arr:
    print(type(x))

In [ ]:
lst3 = [2.13, 7.272, 3, 4.321, 11.234, 101]

np_arr2 = np.array(lst3)

print(np_arr2)
print(np_arr2.dtype)

print(type(np_arr2[2]))

In [ ]:
import numpy as np

lst11 = [[1,2,3,4], [10,20,30,40]]

np_arr11 = np.array(lst11,dtype = int)

In [ ]:
np_arr = np.random.randint(1,100,48)
print(np_arr)

In [ ]:
print(np_arr.shape)

In [ ]:
np_arr_rs = np_arr.reshape(2,2,3,4)
print(np_arr_rs)
print(type(np_arr_rs))

In [ ]:
# Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data
# type of the array:

print(np_arr_rs.shape)

In [ ]:
print(np_arr_rs.dtype)

In [ ]:
# Creating ndarrays The easiest way to create an array is to use the array function. This accepts any sequence-like object
# (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good
# candidate for conversion:

lst1 = [1,2,3,4]

nump_arr = np.array(lst1)

print(nump_arr)
print(type(nump_arr))
print(nump_arr.shape)
print(f'Dimensions of nump_arr is {nump_arr.ndim}.')

In [ ]:
# Note, how for a one dimensional array, the shape tuple is (4,) but the dimensions are 1.

In [ ]:


nump_arr = np.arange(8).reshape(4,2)

print(nump_arr.shape)
print(nump_arr.ndim)
print(nump_arr)

In [ ]:
# Nested sequences, like a list of equal-length lists, will be converted into a multi-dimensional array:

In [ ]:
lst2 = [[1,2,3,4], [10,20,30,40]]

nump_arr2 = np.array(lst2)

print(nump_arr2)
print(type(nump_arr2))
print(nump_arr2.shape)
print(f'Dimensions of nump_arr2 is {nump_arr2.ndim}.')

In [ ]:
print(nump_arr2)
nump_arr2

In [ ]:
# Note the output when outputting nump_arr2 on the notebook. It specifies that this is an array - but note the return of the
# comma!! It doesnt make a difference since we know that this is an array but just pointing out the difference in the 
# view of both commands.

In [ ]:
#asarray

In [ ]:
import numpy as np

lst1 = [1,2,3,4]
np_array = np.array(lst1)
np_asarray = np.asarray(lst1)

print(np_array)
print(type(np_array))

print(np_asarray)
print(type(np_asarray))

In [ ]:
lst1[0] = 100

print(lst1)
print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 101
print(lst1)
print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 1
print(np_array)

In [ ]:
np_asarray[0] = 1001

print(lst1)
print(np_array)
print(np_asarray)


###### np.array from list - change to either list or array does not affect the other
###### np.asarray from list - change to either list or array does not affect the other

##### np.array from array - change to either array does not affect the other
##### np.asarray from array - change to either DOES affect the other

In [ ]:
lst2 = [[1,2,3,4], [100,200,300,400]]

np_lst = np.array(lst2)

In [ ]:
print(np_lst)
print(type(np_lst))

In [ ]:
np_array_lst = np.array(np_lst)
np_asarray_lst = np.asarray(np_lst)

print(np_array_lst, type(np_array_lst))
print(np_asarray_lst, type(np_asarray_lst))

In [ ]:
np_lst[0][1] = 1000

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
np_array_lst[0][0] = 1111

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
np_asarray_lst[0][0] = 2222

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
# Before we go on - lets make the axis of Numpy clear. 
import numpy as np

arr = np.arange(1,25)
arr

In [ ]:
arr1 = arr.reshape(3,8)
arr1

In [ ]:
arrx = np.arange(1,49)
arrx

In [ ]:
arr2 = arrx.reshape(2,3,8)
arr2

In [ ]:
arr2x = np.arange(1,49).reshape(2,2,4,3)

arr2x

In [ ]:
import numpy as np

arr_trial = np.arange(1,97).reshape(2,2,4,2,3)

print(arr_trial)

In [ ]:
arr_trial = np.arange(1,97).reshape(4,2,12)

print(arr_trial)
print(arr_trial.ndim)

In [ ]:
print('arr :', arr, '\n','_'*125)
print('arr1 :', arr1, '\n','_'*125)
print('arr2 :', arr2, '\n','_'*125)

In [ ]:
arr2 = arr.reshape(2,3,4)
print('arr2 :', arr2, '\n','_'*125)


In [ ]:
arr3 = arr.reshape(2,4,3)
print(arr3)

In [ ]:
arr4 = arr.reshape(4,3,2)
print(arr4)

In [ ]:
print(arr)

In [ ]:
print('Sum Arr', np.sum(arr, axis = 0)) # 1D Array has no axis 1.

In [ ]:
print(arr4)
print(arr4.shape)

In [ ]:
print(np.sum(arr4))

In [ ]:
print('sum Axis 0', np.sum(arr4, axis = 0))

In [ ]:
ax0 = np.sum(arr4, axis = 0)

print(ax0)
print(ax0.shape)

In [ ]:
print(arr4)
print(arr4.shape)

In [ ]:
print(arr4)

In [ ]:
arr_col = np.sum(arr4, axis = 1)
print(arr_col)
print(arr_col.shape)

In [ ]:
print(arr4)

print('Sum Axis 2', np.sum(arr4, axis = 2)) # 4,3,2     - 4,3

In [ ]:
arr6 = np.arange(1,13).reshape(3,2,2)

print(arr6)

In [ ]:
arr = np.arange(1,49)
arr5 = arr.reshape(3,4,2,2)
print('arr5 :', arr5)
print('Sum Axis 3', np.sum(arr5, axis = 0))

In [ ]:
print(np.sum(arr6,axis = 2))

In [ ]:
print(np.sum(arr6, axis = 1))

In [ ]:
print(np.sum(arr6))

In [ ]:
import numpy as np

num_arr = np.arange(1,2, 0.02)

print(num_arr)
print(type(num_arr))

In [ ]:
python_range = list(range(1,20,1))
print(python_range)

### Homogeneous n-dimensional vectors:

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape(using tuples for shape).

In [ ]:
np_zero = np.zeros(10)

print(np_zero)



In [ ]:
np_zero6x2 = np.zeros((2,6))

print(np_zero6x2)

In [ ]:
#Note above how the shape is a tuple. 

In [ ]:
np_one = np.ones(10)
print(np_one)

In [ ]:
np_one6x2 = np.ones((2,6,10), dtype = int)

print(np_one6x2)

In [ ]:
np_full_5 = np.full(5,10)

print(np_full_5)

In [ ]:
np_full_a = np.full(10, 'a')

In [ ]:
print(np_full_a)

In [ ]:
np_full6x2_5 = np.full((2,6), 5)

print(np_full6x2_5)

In [ ]:
# Empty creates an array without initializing its values to any particular value. To create a higher dimensional array
# with these methods, use a tuple for shape.

In [ ]:
np_nan = np.full(10,None)

print(np_nan)

print(type(np_nan[0]))

In [1]:
import numpy as np

np_empty = np.empty(10)
print(np_empty)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
np_empty6x2 = np.empty((2,6))
print(np_empty6x2)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.20161118e-306
  1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 1.29061142e-306 1.27951678e-307
  9.34562258e-307 8.45603441e-307]]


In [ ]:
#Note that the numpy empty does not actually have empty values - it does create the array of desired shape and size but with
# arbitary values. It is slightly faster to initialise than np.zeros and np.ones especially for larger arrays. 

#### Note that for each of np.zeros, np.ones, np.full and np.empty there are np.zeros_like, ones_like, full_like and empty_like which behave just like the difference between np.array and np.asarray i.e. if the matrix is already an array, then does not create a copy but just gives array like funcitonality.

In [ ]:
#Matrix Functions

In [3]:
#1. The identity matrix:
# In linear algebra, the identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros
# elsewhere.

np_id = np.identity(5)

print(np_id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Note that by default the 1s and 0s are float type. 

In [ ]:
np_id_int = np.identity(5, dtype = int)

print(np_id_int)

In [4]:
np_id_bool = np.identity(5,dtype= bool)

print(np_id_bool)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [5]:
# 2. Function ‘eye’:
# It is used to return a 2-D array with ones on the diagonal and zeros elsewhere. Unlike identity, array does not necessarily
# have to be square.

np_eye_1 = np.eye(5)

print(np_eye_1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
np_eye_5x4 = np.eye(5,4, dtype = int)

print(np_eye_5x4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [ ]:
# We can also specify the diagnol in the eye function unlike the identity function. 0 is the default, Positive values are
# integers above the main diagonal and negative values are integers below the main diagonal. 

In [12]:
np_eye_8x6_0 = np.eye(6,6,0)

print(np_eye_8x6_0)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [13]:
np_eye_8x6_p1 = np.eye(6,6,1)

print(np_eye_8x6_p1)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
np_eye_8x6_p2 = np.eye(6,6,2)

print(np_eye_8x6_p2)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
np_eye_8x6_n1 = np.eye(6,6,-1)

print(np_eye_8x6_n1)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [21]:
np_eye_8x6_n2 = np.eye(6,6,-2)

print(np_eye_8x6_n2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [ ]:
# 3. Function diag:
# The diag function takes two arguments:
# ● An ndarray v.
# ● An integer k (default = 0). If ‘v’ is dimension is 1 then the function constructs a matrix where its diagonal number k 
# is formed by the elements of the vector ‘v’. If a is a matrix (dimension 2) then the function extracts the elements of
# the kth diagonal in a one-dimensional vector.

In [30]:
np_diag = np.diag(list(range(1,10)))

print(np_diag)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [28]:
np_array_1 = np.ones((3,3))


print(np_array_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
np_diag1 = np.diag(np_diag, k=5)

print(np_diag1)

[0 0 0 0]


In [25]:
np_array_1 = np.diag([1,3,5])

In [26]:
np_diag1 = np.diag(np_array_1)

print(np_array_1)

[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [35]:
print(np_diag1)

[0 0 0 0]


In [36]:
np_arr_lst = np.array([[1,2,3], [10,20,30], [100,200,300]])

print(np_arr_lst)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [37]:
np_diag_l = np.diag(np_arr_lst)

print(np_diag_l)

[  1  20 300]


In [40]:
np_diag_2 = np.diag(np_arr_lst, 1)

print(np_diag_2)

[ 2 30]


In [3]:
import numpy as np

np_ones = np.ones((3,3))

print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#4. Function ‘fromfunction’:
# Construct an array by executing a function over each coordinate. Let’s create a vector-based on its indices.

import numpy as np

np_ffunc = np.fromfunction(lambda x,y : x-y, (3,3))

print(np_ffunc)

[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]


In [ ]:
#Remember here that the co-ordinates x,y for each element are as follows:

0,0   0,1   0,2
1,0   1,1   1,2
2,0   2,1   2,2

In [8]:
np_ffuncXY2 = np.fromfunction(lambda x,y,z : x*y+z, (3,3,3))

print(np_ffuncXY2)

[[[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]

 [[0. 1. 2.]
  [1. 2. 3.]
  [2. 3. 4.]]

 [[0. 1. 2.]
  [2. 3. 4.]
  [4. 5. 6.]]]


In [5]:
# 0,0,0  0,0,1  0,0,2
# 0,1,0  0,1,1, 0,1,2
# 0,2,0, 0,2,1, 0,2,2

# 1,0,0  1,0,1  1,0,2
# 1,1,0  1,1,1, 1,1,2
# 1,2,0, 1,2,1, 1,2,2

# 2,0,0  2,0,1  2,0,2
# 2,1,0  2,1,1, 2,1,2
# 2,2,0, 2,2,1, 2,2,2

SyntaxError: invalid syntax (<ipython-input-5-8a9ca8a166cc>, line 5)

In [ ]:
import numpy as np

np_ffunct_gte = np.fromfunction(lambda x,y : x >= y, (3,3))

print(np_ffunct_gte)

In [ ]:
# Aggregation methods:

np_sample = np.arange(24).reshape(2,3,4)

print(np_sample)

In [ ]:
test = list(range(1,20,0.2))

In [ ]:
test1 = np.arange(1,5,0.2)

print(test1)

In [ ]:
# ● ndarray.sum: Return the sum of the array elements over the given axis.
print(np_sample)

In [ ]:
print(np_sample.sum()) # - With no axis specified, sums all the elements of the 0 axis.

In [ ]:
np_s_a0 = np_sample.sum(0) # - with axis specified sums elements of specified axis or you could say collapses specified axis

print(np_s_a0)
print(np_s_a0.ndim)

In [ ]:
print(np_sample)
print(np_sample.ndim)

In [ ]:
np_s_a1 = np_sample.sum(1)

print(np_s_a1)
print(np_s_a1.ndim)

In [ ]:
np_s_a2 = np_sample.sum(2)

print(np_s_a2)
print(np_s_a2.ndim)

In [ ]:
print(np_sample)

In [41]:
# ● ndarray.product: Return the product of the array elements over the given axis.

np_sample_2 = np.arange(1,11).reshape(2,5)

print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [42]:
np_prod = np_sample_2.prod()

print(np_prod)

3628800


In [43]:
print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
np_prod_0 = np_sample_2.prod(0)

print(np_prod_0)

[ 6 14 24 36 50]


In [45]:
np_prod_1 = np_sample_2.prod(1)

print(np_prod_1)

[  120 30240]


In [50]:
np_rand_sample = np.random.randint(1,100,24).reshape(2,3,4)

print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [ ]:
# ● ndarray.max: Return the maximum along the given axis.
# ● ndarray.argmax: Return indices of the maximum values along the given axis

In [51]:
print(np_rand_sample.max()) #without any axis - maximum of array

99


In [52]:
print(np_rand_sample.argmax()) # Index position of maximum number - without any axis > index value of max number (flattened
# array)

12


In [53]:
print(np_rand_sample.flatten())

[18 77 22 78 59 66 76 56 88 14 88 54 99 24  2 29 13 64 47 30 49 32 76 17]


In [54]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [55]:
print(np_rand_sample.max(0)) # with axis 0

[[99 77 22 78]
 [59 66 76 56]
 [88 32 88 54]]


In [56]:
print(np_rand_sample.argmax(0)) # with axis 0

[[1 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]


In [57]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [58]:
print(np_rand_sample.max(1))
print(np_rand_sample.argmax(1))

[[88 77 88 78]
 [99 64 76 30]]
[[2 0 2 0]
 [0 1 2 1]]


In [59]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [60]:
print(np_rand_sample.max(2))
print(np_rand_sample.argmax(2))

[[78 76 88]
 [99 64 76]]
[[3 2 0]
 [0 1 2]]


In [61]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [ ]:
# ● ndarray.min: Return the minimum along the given axis.
# ● ndarray.argmin: Return indices of the minimum values along the given axis.

In [62]:
print(np_rand_sample.min())
print(np_rand_sample.argmin())
print(np_rand_sample.flatten())

2
14
[18 77 22 78 59 66 76 56 88 14 88 54 99 24  2 29 13 64 47 30 49 32 76 17]


In [63]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [64]:
print(np_rand_sample.min(0))
print(np_rand_sample.argmin(0))

[[18 24  2 29]
 [13 64 47 30]
 [49 14 76 17]]
[[0 1 1 1]
 [1 1 1 1]
 [1 0 1 1]]


In [65]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [66]:
print(np_rand_sample.min(1))
print(np_rand_sample.argmin(1))

[[18 14 22 54]
 [13 24  2 17]]
[[0 2 0 2]
 [1 0 0 2]]


In [67]:
print(np_rand_sample.min(2))
print(np_rand_sample.argmin(2))

[[18 56 14]
 [ 2 13 17]]
[[0 3 1]
 [2 0 3]]


In [68]:
# ● ndarray.mean: Returns the average of the array elements along the given axis.

print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [69]:
print(np_rand_sample.mean()) #without axis - mean of all elements.

49.083333333333336


In [70]:
print(np_rand_sample.mean(0))

[[58.5 50.5 12.  53.5]
 [36.  65.  61.5 43. ]
 [68.5 23.  82.  35.5]]


In [71]:
print(np_rand_sample.mean(1))

[[55.         52.33333333 62.         62.66666667]
 [53.66666667 40.         41.66666667 25.33333333]]


In [72]:
print(np_rand_sample.mean(2))

[[48.75 64.25 61.  ]
 [38.5  38.5  43.5 ]]


In [ ]:
# ● ndarray.cumsum: Return the cumulative sum of the elements along the given axis.

In [73]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [74]:
print(np_rand_sample.cumsum())

[  18   95  117  195  254  320  396  452  540  554  642  696  795  819
  821  850  863  927  974 1004 1053 1085 1161 1178]


In [75]:
print(np_rand_sample.cumsum(0))

[[[ 18  77  22  78]
  [ 59  66  76  56]
  [ 88  14  88  54]]

 [[117 101  24 107]
  [ 72 130 123  86]
  [137  46 164  71]]]


In [76]:
print(np_rand_sample.cumsum(1))

[[[ 18  77  22  78]
  [ 77 143  98 134]
  [165 157 186 188]]

 [[ 99  24   2  29]
  [112  88  49  59]
  [161 120 125  76]]]


In [78]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [79]:
print(np_rand_sample.cumsum(2))

[[[ 18  95 117 195]
  [ 59 125 201 257]
  [ 88 102 190 244]]

 [[ 99 123 125 154]
  [ 13  77 124 154]
  [ 49  81 157 174]]]


In [ ]:
# ● ndarray.cumprod: Return the cumulative product of the elements along the given axis.

In [80]:
np_sample_cd = np.random.randint(1,10, 12).reshape(2,2,3)

print(np_sample_cd)

[[[2 2 1]
  [3 3 2]]

 [[8 9 4]
  [6 7 2]]]


In [81]:
print(np_sample_cd.cumprod())

[      2       4       4      12      36      72     576    5184   20736
  124416  870912 1741824]


In [82]:
print(np_sample_cd.cumprod(0))

[[[ 2  2  1]
  [ 3  3  2]]

 [[16 18  4]
  [18 21  4]]]


In [83]:
print(np_sample_cd)

[[[2 2 1]
  [3 3 2]]

 [[8 9 4]
  [6 7 2]]]


In [84]:
print(np_sample_cd.cumprod(1))

[[[ 2  2  1]
  [ 6  6  2]]

 [[ 8  9  4]
  [48 63  8]]]


In [85]:
print(np_sample_cd.cumprod(2))

[[[  2   4   4]
  [  3   9  18]]

 [[  8  72 288]
  [  6  42  84]]]


In [ ]:
# ● ndarray.var: Returns the variance of the array elements, along the given axis.
# ● ndarray.std: Returns the standard deviation of the array elements along the given axis.

In [86]:
print(np_rand_sample)

[[[18 77 22 78]
  [59 66 76 56]
  [88 14 88 54]]

 [[99 24  2 29]
  [13 64 47 30]
  [49 32 76 17]]]


In [87]:
print('mean : ', np_rand_sample.mean())

mean :  49.083333333333336


In [88]:
print('Variance : ', np_rand_sample.var())

Variance :  768.1597222222222


In [89]:
print('Standard Deviation : ', np_rand_sample.std())

Standard Deviation :  27.715694510912442


In [90]:
print('Variance')
print(np_rand_sample.var(0))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(0))

Variance
[[1.64025e+03 7.02250e+02 1.00000e+02 6.00250e+02]
 [5.29000e+02 1.00000e+00 2.10250e+02 1.69000e+02]
 [3.80250e+02 8.10000e+01 3.60000e+01 3.42250e+02]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[40.5 26.5 10.  24.5]
 [23.   1.  14.5 13. ]
 [19.5  9.   6.  18.5]]


In [91]:
print('Variance')
print(np_rand_sample.var(1))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(1))

Variance
[[ 824.66666667  754.88888889  824.          118.22222222]
 [1243.55555556  298.66666667  926.88888889   34.88888889]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[28.71701006 27.47524138 28.70540019 10.87300429]
 [35.26408308 17.2819752  30.44484996  5.90668172]]


In [92]:
print('Variance')
print(np_rand_sample.var(2))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(2))

Variance
[[ 828.6875   59.1875  929.    ]
 [1323.25    361.25    480.25  ]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[28.7869328   7.69334128 30.47950131]
 [36.37650341 19.00657781 21.914607  ]]


### Data Types for ndarrays

In [ ]:
# The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to
# interpret a chunk of memory as a particular type of data:

In [ ]:
import numpy as np
import sys
np_arr1 = np.array([1,2,3], dtype = 'float16')

In [ ]:
print(np_arr1.dtype)
print(np_arr1)

In [ ]:
np_arr2 = np.array([10,-4,3], dtype = 'int8')

print(np_arr2.dtype)
print(np_arr2)

print(sys.getsizeof(np_arr2[0]))
print(sys.getsizeof(10))

In [ ]:
# Type              Type code           Description
# int8, uint8       i1, u1              Signed and unsigned 8-bit (1byte) integer types
# int16, uint16     i2, u2              Signed and unsigned 16-bit integer types
# int32, uint32     i4, u4              Signed and unsigned 32-bit integer types
# int64, uint64     i8, u8              Signed and unsigned 64-bit integer types
# float16           f2                  Half-precision floating point
# float32           f4 or f             Standard single-precision floating point; compatible with C float
# float64           f8 or d             Standard double-precision floating point; compatible with C double
#                                       and Python float object
# float128          f16 or g            Extended-precision floating point
# complex64,        c8, c16, c32        Complex numbers represented by two 32, 64, or 128 floats respectively
# complex128,
# complex256
# bool              ?                   Boolean type storing True and False values
# object            O                   Python object type; a value can be any Python object
# string_           S                   Fixed-length ASCII string type (1 byte per character); for example, to create a
#                                       string dtype with length 10, use 'S10'
# unicode_          U                   Fixed-length Unicode type (number of bytes platform specific); same specification
#                                       semantics as string_ (e.g., 'U10')

# Note: It’s important to be cautious when using the numpy string_ type, as string data in NumPy is fixed size and may
# truncate input without warning

### Arithmetic with NumPy

In [ ]:
# Arrays Arrays are important because they enable you to express batch operations on data without writing any for loops. 
# NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation
# element-wise:

In [9]:
np_arr1 = np.array([[1,2,3], [4,5,6]])

np_arr2 = np.array([[2,4,6], [8,10,12]])

print(np_arr1)
print(np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [10]:
print(np_arr1 * np_arr2)

[[ 2  8 18]
 [32 50 72]]


In [11]:
print(np_arr2 - np_arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [12]:
print(np_arr1)

[[1 2 3]
 [4 5 6]]


In [13]:
print(np_arr1*2)

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
print(np_arr1)
print(np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
print(np_arr1 * np_arr2)

In [ ]:
print((np_arr1*np_arr2)**1/2)

In [ ]:
# Comparisons between arrays of the same size yield boolean arrays:

In [16]:
print(np_arr1)
print(np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
print(np_arr1 > np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[False False False]
 [False False False]]


In [17]:
arrtest = np.arange(1,11).reshape(2,5)

arrtest

print(arrtest.ndim)
print(arrtest)

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
np_arr1 = np.random.randint(1,100,6).reshape(2,3)

np_arr2 = np.random.randint(1,100,6).reshape(2,3)

print(np_arr1)
print(np_arr2)

[[85  9 30]
 [23 85 98]]
[[32 31 82]
 [29 36 87]]


In [20]:
np_trufals = np_arr1 > np_arr2

print(np_trufals)

[[ True False False]
 [False  True  True]]


In [21]:
# Uncommon dimensions arrays are 'broadcast'. E.g.

import numpy as np

# However, broadcasting needs to follow certain rules. 

# Arrays are broadcastable if:

# Arrays have exactly the same shape.

np_arr_so = np.arange(1,7).reshape(3,2)
np_arr_lo = np.arange(10,70,10).reshape(3,2)

print(np_arr_so)
print(np_arr_lo)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
print(np_arr_so*np_arr_lo)

In [22]:
# Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

np_arr_so = np.arange(3).reshape(1,3)
print(np_arr_so)

[[0 1 2]]


In [23]:
np_arr_lo = np.arange(0,60,10).reshape(2,3)
print(np_arr_lo)

[[ 0 10 20]
 [30 40 50]]


In [24]:
print(np_arr_so*np_arr_lo)

[[  0  10  40]
 [  0  40 100]]


In [27]:
arr_lo = np.arange(1,385).reshape(2,4,6,8)
arr_so = np.arange(1,17).reshape(2,1,1,8)

print(arr_lo * arr_so)

[[[[   1    4    9   16   25   36   49   64]
   [   9   20   33   48   65   84  105  128]
   [  17   36   57   80  105  132  161  192]
   [  25   52   81  112  145  180  217  256]
   [  33   68  105  144  185  228  273  320]
   [  41   84  129  176  225  276  329  384]]

  [[  49  100  153  208  265  324  385  448]
   [  57  116  177  240  305  372  441  512]
   [  65  132  201  272  345  420  497  576]
   [  73  148  225  304  385  468  553  640]
   [  81  164  249  336  425  516  609  704]
   [  89  180  273  368  465  564  665  768]]

  [[  97  196  297  400  505  612  721  832]
   [ 105  212  321  432  545  660  777  896]
   [ 113  228  345  464  585  708  833  960]
   [ 121  244  369  496  625  756  889 1024]
   [ 129  260  393  528  665  804  945 1088]
   [ 137  276  417  560  705  852 1001 1152]]

  [[ 145  292  441  592  745  900 1057 1216]
   [ 153  308  465  624  785  948 1113 1280]
   [ 161  324  489  656  825  996 1169 1344]
   [ 169  340  513  688  865 1044 1225 1408]
   [

In [28]:
np_arr_lo = np.arange(0,60,10).reshape(3,2)
np_arr_so = np.arange(2).reshape(1,2)

print(np_arr_lo)
print(np_arr_so)

[[ 0 10]
 [20 30]
 [40 50]]
[[0 1]]


In [29]:
print(np_arr_lo*np_arr_so)

[[ 0 10]
 [ 0 30]
 [ 0 50]]


In [30]:
np_arr_so = np.arange(6).reshape(1,2,3)
np_arr_so

array([[[0, 1, 2],
        [3, 4, 5]]])

In [31]:
np_arr_lo = np.arange(0,120,10).reshape(2,2,3)
np_arr_lo

array([[[  0,  10,  20],
        [ 30,  40,  50]],

       [[ 60,  70,  80],
        [ 90, 100, 110]]])

In [ ]:
print(np_arr_so+np_arr_lo)

In [41]:
# Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated
# property is true.

np_arr_so = np.arange(1,7).reshape(1,1,2,3)
print(np_arr_so)

[[[[1 2 3]
   [4 5 6]]]]


In [42]:
np_arr_lo = np.arange(1,37).reshape(2,3,2,3)
print(np_arr_lo)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]

  [[25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]]]]


In [43]:
np_arr_so*np_arr_lo

array([[[[  1,   4,   9],
         [ 16,  25,  36]],

        [[  7,  16,  27],
         [ 40,  55,  72]],

        [[ 13,  28,  45],
         [ 64,  85, 108]]],


       [[[ 19,  40,  63],
         [ 88, 115, 144]],

        [[ 25,  52,  81],
         [112, 145, 180]],

        [[ 31,  64,  99],
         [136, 175, 216]]]])

In [44]:
np_arr_so = np_arr_so.reshape(2,3)
print(np_arr_so)

[[1 2 3]
 [4 5 6]]


In [45]:
print(np_arr_so*np_arr_lo)

[[[[  1   4   9]
   [ 16  25  36]]

  [[  7  16  27]
   [ 40  55  72]]

  [[ 13  28  45]
   [ 64  85 108]]]


 [[[ 19  40  63]
   [ 88 115 144]]

  [[ 25  52  81]
   [112 145 180]]

  [[ 31  64  99]
   [136 175 216]]]]


In [46]:
np_append = np.arange(1,13).reshape(2,2,3)

In [58]:
np_append1 = np.arange(1,5).reshape(2,2)

In [59]:
print(np_append)
print(np_append1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2]
 [3 4]]


In [53]:
np_append + np_append1

array([[[ 2,  3,  4],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [14, 15, 16]]])

In [ ]:
# However, broadcasting follows certain rules:

# An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly
# 1.

# If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that
# dimension.

# Array with smaller ndim than the other is prepended with '1' in its shape.

# Size in each dimension of the output shape is maximum of the input sizes in that dimension.


### Basic Indexing and Slicing

In [ ]:
#NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual
# elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [60]:
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
print(arr1[5])

5


In [62]:
print(arr1[2:4])

[2 3]


In [ ]:
# Slice assignment

In [68]:
arr1[2:7] = 11

print(arr1)

[ 0  1 11 11 11 11 11  7  8  9]


In [67]:
list1 = list(range(10))
print(list1)
list1[2:4] = 11,
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 11, 4, 5, 6, 7, 8, 9]


In [ ]:
# As you can see, if you assign a scalar value to a slice of an array, as in arr[2:4] = 11, the value is propagated (or 
# broadcasted henceforth) to the entire selection. While for lists, the value(s) of the iterable replace(s) the slice.

In [ ]:
# An important first distinction from Python’s built-in lists is that array slices are views on the original array. This
# means that the data is not copied, and any modifications to the view will be reflected in the source array. To give
# an example of this, first create a slice of arr:

In [69]:
arr = np.arange(11)
arr_slice = arr[5:8]
print(arr)
print(arr_slice)

[ 0  1  2  3  4  5  6  7  8  9 10]
[5 6 7]


In [70]:
arr_slice[1] = 6789
print(arr)
print(arr_slice)

[   0    1    2    3    4    5 6789    7    8    9   10]
[   5 6789    7]


In [72]:
list1 = list(range(11))
lst_slice = list1[5:8]
print(list1)
print(lst_slice)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 6, 7]


In [73]:
lst_slice[1] = 6789
print(lst_slice)
print(list1)

[5, 6789, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# To copy an array or its slice you have to exlicitly copy.

In [74]:
arr = np.arange(11)
print(arr)
arr_slice = arr[5:8].copy()

print(arr_slice)

[ 0  1  2  3  4  5  6  7  8  9 10]
[5 6 7]


In [75]:
arr_slice[1] = 6789

print(arr_slice)
print(arr)

[   5 6789    7]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Accessing values in nested arrays.

In [77]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

print(lst1[1][1])

5


In [76]:
arr_hdim = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_hdim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(arr_hdim[1][1])

5


In [82]:
# Numpy allows you to use easier syntax to access elements in nested arrays.

print(arr_hdim[0,2])

3


In [ ]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

print(lst1[1][1])


In [ ]:
print(lst1[1,1])

In [83]:
#Indexing with slices

#Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
print(arr[1:6])

[1 2 3 4 5]


In [85]:
# Consider a two-dimensional array. Slicing this array is a bit different:
 
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [86]:
print(arr_2d[:2]) 

# arr_2d[0, 1]
# arr_2d[:2,:]

[[1 2 3]
 [4 5 6]]


In [90]:
arr_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# As we see, the array has been sliced on axis 0

In [89]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
# As the syntax for multiple indexes seen previously, we can pass multiple slices as well. 

print(arr_2d[:2])

[[1 2 3]
 [4 5 6]]


In [92]:
print(arr_2d[:2, :2])

[[1 2]
 [4 5]]


In [93]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
# or

print(arr_2d[:2,1:])

[[2 3]
 [5 6]]


In [ ]:
# When slicing like this, you always obtain array views of the same number of dimensions

In [ ]:
# By mixing integer indexes and slices, you get lower dimensional slices

In [95]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
print(arr_2d[1,1:])

[5 6]


In [ ]:
# Here we first selected the 1st index on axis 0 and then sliced from 1st index to end along axis 1

In [97]:
# Another example, slice from 1st index to end along axis 0 and then index 2 along axis 1
print(arr_2d[1:])

[[4 5 6]
 [7 8 9]]


In [98]:
print(arr_2d[1:,2])

[6 9]


In [99]:
arr_3d = np.arange(24).reshape(2,3,4)

print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [100]:
print(arr_3d[1][1][2])

18


In [101]:
print(arr_3d[1:,:2,0])

[[12 16]]


### Boolean Indexing

In [ ]:
# Let’s consider an example where we have some data in an array and an array of names with duplicates. 

In [102]:
names = np.array(['Bob', 'John', 'Steve', 'Will', 'Bob', 'Steve', 'Bob'])
print(names)

['Bob' 'John' 'Steve' 'Will' 'Bob' 'Steve' 'Bob']


In [103]:
# Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with
# the string 'Bob' yields a boolean array:
print(names == 'Bob')

[ True False False False  True False  True]


In [104]:
data = np.random.randint(1,10,49).reshape(7,7)

print(data)

[[6 2 5 9 2 7 8]
 [4 2 6 1 4 1 4]
 [4 2 7 2 1 7 1]
 [7 7 1 6 3 1 2]
 [8 6 2 2 5 3 1]
 [1 7 7 4 6 5 1]
 [8 2 8 5 9 1 1]]


In [ ]:
# We can use the values from the boolean array returned from the comparison operator == performed on 'names' array to 
# index from another array data.

In [105]:
print(names=='Bob')

[ True False False False  True False  True]


In [113]:
data1 = data[2]

print(data1)

[4 2 7 2 1 7 1]


In [127]:
lst1 = list('abcdefg')

lst2 = []

for x in lst1:
    for y in range(len(lst1)):
        lst2.append(x*(y+1))
print(lst2)

['a', 'aa', 'aaa', 'aaaa', 'aaaaa', 'aaaaaa', 'aaaaaaa', 'b', 'bb', 'bbb', 'bbbb', 'bbbbb', 'bbbbbb', 'bbbbbbb', 'c', 'cc', 'ccc', 'cccc', 'ccccc', 'cccccc', 'ccccccc', 'd', 'dd', 'ddd', 'dddd', 'ddddd', 'dddddd', 'ddddddd', 'e', 'ee', 'eee', 'eeee', 'eeeee', 'eeeeee', 'eeeeeee', 'f', 'ff', 'fff', 'ffff', 'fffff', 'ffffff', 'fffffff', 'g', 'gg', 'ggg', 'gggg', 'ggggg', 'gggggg', 'ggggggg']


In [129]:
arr_alpha = np.array(lst2).reshape(7,7)

print(arr_alpha)

[['a' 'aa' 'aaa' 'aaaa' 'aaaaa' 'aaaaaa' 'aaaaaaa']
 ['b' 'bb' 'bbb' 'bbbb' 'bbbbb' 'bbbbbb' 'bbbbbbb']
 ['c' 'cc' 'ccc' 'cccc' 'ccccc' 'cccccc' 'ccccccc']
 ['d' 'dd' 'ddd' 'dddd' 'ddddd' 'dddddd' 'ddddddd']
 ['e' 'ee' 'eee' 'eeee' 'eeeee' 'eeeeee' 'eeeeeee']
 ['f' 'ff' 'fff' 'ffff' 'fffff' 'ffffff' 'fffffff']
 ['g' 'gg' 'ggg' 'gggg' 'ggggg' 'gggggg' 'ggggggg']]


In [114]:
print(names == 'Bob')

[ True False False False  True False  True]


In [115]:
print(data1[names == 'Bob'])

[4 1 1]


In [117]:
print(data)

[[6 2 5 9 2 7 8]
 [4 2 6 1 4 1 4]
 [4 2 7 2 1 7 1]
 [7 7 1 6 3 1 2]
 [8 6 2 2 5 3 1]
 [1 7 7 4 6 5 1]
 [8 2 8 5 9 1 1]]


In [116]:
print(data[names == 'Bob'])

[[6 2 5 9 2 7 8]
 [8 6 2 2 5 3 1]
 [8 2 8 5 9 1 1]]


In [120]:
data1n = names == 'Bob'

print(data1n)

[ True False False False  True False  True]


In [130]:
print(arr_alpha[names == 'Bob', names=='Bob'])

['a' 'eeeee' 'ggggggg']


In [132]:
# Arange function in Numpy. Takes 4 arguments

#1. Start - Optional - defaults to 0
#2. Stop - Mandatory
#3. Step - Optional - Defaults to 1 but can take floating point numbers as a step (Unlike built-in range function of Python)
#4. dtype - Optional


np_arr_dec = np.arange(1,3,0.01)

print(np_arr_dec)

[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55
 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69
 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83
 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97
 1.98 1.99 2.   2.01 2.02 2.03 2.04 2.05 2.06 2.07 2.08 2.09 2.1  2.11
 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19 2.2  2.21 2.22 2.23 2.24 2.25
 2.26 2.27 2.28 2.29 2.3  2.31 2.32 2.33 2.34 2.35 2.36 2.37 2.38 2.39
 2.4  2.41 2.42 2.43 2.44 2.45 2.46 2.47 2.48 2.49 2.5  2.51 2.52 2.53
 2.54 2.55 2.56 2.57 2.58 2.59 2.6  2.61 2.62 2.63 2.64 2.65 2.66 2.67
 2.68 2.69 2.7  2.71 2.72 2.73 2.74 2.75 2.76 2.77 2.78 2.79 2.8  2.81
 2.82 2.83 2.84 2.85 2.86 2.87 2.88 2.89 2.9  2.91 2.92 2.93 2.94 2.95
 2.96 

In [ ]:
range_1 = list(range(1,3,0.1))
print(list(range_1))

In [ ]:
range_2 = list(range(1,3,1))
print(list(range_2))

In [ ]:
# linspace function - returns evenly spaced equidistant number numbers between a specified range.

In [93]:
# It takes 7 arguments.

#1. Start - Mandatory
#2. Stop - Mandatory
#3. Num - Optional - Number of samples required between the range/interval. By default set to 50
#4. endpoint - Optional - By default set to true and includes the endpoint(i.e. stop value) - if set to False, returns
# equidistant numbers not including the endpoint/stop value.
#5 retstep - Optional - Default is False. If set to true, returns the samples and the step value (distance between samples)
#6 dtype - Optional - By default datatype will be inferred. However, for int datatype, float will be considered even if 
# start and stop are int.
#7 axis - Optional - By default 0 axis. Only useful in case start and stop are array-like.

In [138]:
arr_lin = np.linspace(0,4)

print(arr_lin)

[0.         0.08163265 0.16326531 0.24489796 0.32653061 0.40816327
 0.48979592 0.57142857 0.65306122 0.73469388 0.81632653 0.89795918
 0.97959184 1.06122449 1.14285714 1.2244898  1.30612245 1.3877551
 1.46938776 1.55102041 1.63265306 1.71428571 1.79591837 1.87755102
 1.95918367 2.04081633 2.12244898 2.20408163 2.28571429 2.36734694
 2.44897959 2.53061224 2.6122449  2.69387755 2.7755102  2.85714286
 2.93877551 3.02040816 3.10204082 3.18367347 3.26530612 3.34693878
 3.42857143 3.51020408 3.59183673 3.67346939 3.75510204 3.83673469
 3.91836735 4.        ]


In [ ]:
# By default creates 50 equidistant samples / points

In [139]:
arr_lin10 = np.linspace(0,20,5) # with num of samples specified

print(arr_lin10)

[ 0.  5. 10. 15. 20.]


In [140]:
arr_lin10_noEP = np.linspace(1,20,5, endpoint=False) #No Endpoint included

In [141]:
print(arr_lin10_noEP)

[ 1.   4.8  8.6 12.4 16.2]


In [142]:
arr_lin10_noEP_wRS = np.linspace(1,20,5, endpoint=False, retstep=True) #With array as 1st element and step value as 2nd
                                                                       # element of tuple.
print(arr_lin10_noEP_wRS)
print(type(arr_lin10_noEP_wRS))

(array([ 1. ,  4.8,  8.6, 12.4, 16.2]), 3.8)
<class 'tuple'>


In [143]:
arr_lin10_int = np.linspace(1,20,5, dtype = int) # With dtype specified.
print(arr_lin10_int)

[ 1  5 10 15 20]


In [144]:
arr_like_lin10 = np.linspace((1,2), (3,4), 10) # Array like start and stop values.
print(arr_like_lin10)

#Note here that default axis is 0. The equidistant numbers are being added along 0 axis

[[1.         2.        ]
 [1.22222222 2.22222222]
 [1.44444444 2.44444444]
 [1.66666667 2.66666667]
 [1.88888889 2.88888889]
 [2.11111111 3.11111111]
 [2.33333333 3.33333333]
 [2.55555556 3.55555556]
 [2.77777778 3.77777778]
 [3.         4.        ]]


In [145]:
arr_like_lin10_ax1 = np.linspace((1,2), (3,4), 10, axis=1) # with equidistant samples added along axis 1

print(arr_like_lin10_ax1)

[[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
  2.33333333 2.55555556 2.77777778 3.        ]
 [2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
  3.33333333 3.55555556 3.77777778 4.        ]]


### Random Module in Numpy

In [146]:
#Randint to generate a random integer
np.random.seed(101)

In [157]:
np.random.seed(101)
result = np.random.randint(1,10,5)

print(result)

# Returns random numbers between specified range and number of values specified in third parameter

[2 7 8 9 5]


In [158]:
print(np.random.randint(1,10)) # Prints 1 number between 0 and 9 - Start not specified defaults to 0, number not specified 
                             # defaults to 1.

9


In [159]:
#rand - For random float values between 0 and 1 only.

result = np.random.rand()

print(result)



0.2661885598416913


In [160]:
print(np.random.rand(3,2,4)) # Can take shape as parameter. Here will return 3 arrays on axis 0, 2 on 1 and 4 on 2

[[[0.77888791 0.89206388 0.0756819  0.82565261]
  [0.02549692 0.5902313  0.5342532  0.58125755]]

 [[0.77471672 0.97791191 0.61159951 0.94628427]
  [0.43289654 0.79182632 0.45650246 0.82667814]]

 [[0.14623959 0.60263149 0.591275   0.44168587]
  [0.49201605 0.73150955 0.82635863 0.0710152 ]]]


In [162]:
#randn function - returns float values in given shape array from a standard normal distribution i.e. 

# Roughly - 65% of the values will be between -1 to 1
# Roughly - 95% of the values will be between -2 to 2
# Roughly - 99% of the values will be between -3 to 3

# If no shape provided will return a single float value.

result = np.random.randn(3,3,3)

print(result)

[[[ 1.02904824 -0.27207863  2.06079718]
  [-1.04686723 -2.27373854  1.2180964 ]
  [-0.66268425  0.42049132 -0.26052634]]

 [[ 0.38978047  0.16424447 -0.37158136]
  [-0.05073897  2.43460129  1.24144018]
  [ 0.1909783  -1.24534738  0.95218288]]

 [[ 1.30138031 -0.16731958  0.05022118]
  [ 1.55678957  1.34543415  1.50173651]
  [-0.63334845 -0.48728117 -1.64746873]]]


In [161]:
#Uniform
import numpy as np

float_val = np.random.uniform(1.0,100.0,10)

print(float_val)

[23.24023181 68.29022715 71.54716055 65.72564701 84.10686889 14.89568148
  2.50425229 34.22026983 79.92857793 86.39060334]


In [163]:
arr1 = np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [164]:
#choice - Choose a random number from an array or integer. 

# Takes only one 1D array or an integer as input from which to chose. 

choice = np.random.choice(arr1)

print(choice)

17


In [166]:
choice = np.random.choice(1000) # If an integer x is specified - treats it as a choice in np.arange(x) i.e from 0 to x-1 e.g.
                              # here - it will choose between 0 to 9.
    
print(choice)

235


In [167]:
choice = np.random.choice(arr1, 5) # Size of choice specified.
print(choice)

[ 4  7 11  5 17]


In [ ]:
# By default - replace parameter is True i.e. if a number has been chosen, it will be put back in the array and has a chance
# to be chosen again. By setting to false - the number is removed from array and wont be chosen again.

arr1 = np.arange(5)

In [196]:
lst1 = []

In [197]:
for x in range(20):
    lst1.append(np.random.choice(arr1, replace = True))

In [198]:
print(lst1)

[17, 19, 6, 10, 0, 19, 13, 5, 6, 6, 9, 1, 7, 14, 7, 15, 0, 9, 19, 2]


In [ ]:
np_arr1 = np.arange(4)

print(np_arr1)

In [188]:
np.random.choice(np_arr1, replace = False)



ValueError: a must be 1-dimensional

In [200]:
# The p parameter takes probabilities i.e. if I had numbers 1 to 5 - in a uniform distribution each would have a 20% chance
# or (0.2 probability). However, if we were to specify the probabilities, it will take those probabilities into account
# while generating random numbers

choice = np.random.choice(np.arange(3), p = [0.1,0.2,0.7], size = 10)

print(choice)

[2 1 2 2 2 2 2 2 2 0]


In [2]:
#permutation - Returns a random permutation of input array or if integer specified random permutation of np.arrange(integer)
import numpy as np

perm = np.random.permutation(10)

print(perm)

[4 6 3 9 0 1 5 7 2 8]


In [3]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [4]:
perm_arr = np.random.permutation(arr) #
print(perm_arr)


# For a multidimensional array - it is only shuffled along the 0 index axis.

[[[ 6  7]
  [ 8  9]
  [10 11]]

 [[18 19]
  [20 21]
  [22 23]]

 [[12 13]
  [14 15]
  [16 17]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]]


In [5]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#any - Returns true if any of the elements in the array are true. 
#all Returns true if all of the elements in the array are true.

In [6]:
print(np.any(arr))

True


In [7]:
print(np.all(arr))

False


In [9]:
arr_zero = np.zeros(5)

print(arr_zero)

[0. 0. 0. 0. 0.]


In [10]:
print(np.any(arr_zero))

False


In [11]:
print(np.all(arr_zero))

False


In [14]:
arr_alt = np.random.randint(0,2,5)

print(arr_alt)

[0 0 1 1 0]


In [15]:
print(np.any(arr_alt))

True


In [16]:
print(np.all(arr_alt))

False


In [18]:
arr_zero_grid = np.zeros((2,3))
print(arr_zero_grid)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(np.any(arr_zero_grid))

False


In [20]:
print(np.all(arr_zero_grid))

False


In [21]:
arr_one_grid = np.ones((2,3))
print(arr_one_grid)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
print(np.any(arr_one_grid))

True


In [23]:
print(np.all(arr_one_grid))

True


In [24]:
arr = np.arange(11)
arr10 = np.arange(11,21)
print(arr)
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [25]:
# Append

arr_n_10 = np.append(arr, arr10)
print(arr_n_10)

# print(arr)
# print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [26]:
arr_1 = np.arange(1,11).reshape(2,5)
arr_2 = np.arange(21,31).reshape(2,5)

print(arr_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
print(arr_2)

[[21 22 23 24 25]
 [26 27 28 29 30]]


In [28]:
arr_1n2 = np.append(arr_1, arr_2, axis = 1)

print(arr_1n2)

[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]]


In [ ]:
#[[1,2,3,4,5]
#[6,7,8,9,10]
#[[21,22,23,24,25]
#[26,27,28,29,30]]



In [29]:
arr_1n2V = np.append(arr_1, arr_2, axis = 0)

print(arr_1n2V)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [34]:
#vstack - stacks arrays vertically

arr_V = np.vstack((arr_1, arr_2))
print(arr_V)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [31]:
arr1x = np.arange(1,6)
arr2x = np.arange(11,16)
print(arr1x)
print(arr2x)

[1 2 3 4 5]
[11 12 13 14 15]


In [33]:
arr_vx = np.vstack((arr1x, arr2x))
print(arr_vx)


[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [36]:
arr1x = np.arange(1,13).reshape(2,2,3)
arr2x = np.arange(11,23).reshape(2,2,3)
print(arr1x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
print(arr2x)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [39]:
arrvx = np.vstack((arr1x,arr2x))

print(arrvx)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [41]:
print(arr1x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
print(arr2x)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [44]:
arr_H = np.hstack((arr1x, arr2x))

print(arr_H)

[[[ 1  2  3]
  [ 4  5  6]
  [11 12 13]
  [14 15 16]]

 [[ 7  8  9]
  [10 11 12]
  [17 18 19]
  [20 21 22]]]


In [45]:
arr1x = np.arange(1,13).reshape(2,2,3)
arr2x = np.arange(11,17).reshape(2,3)
print(arr1x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
print(arr2x)

[[11 12 13]
 [14 15 16]]


In [53]:
arr_2n3 = np.append(arr1x,arr2x)

print(arr_2n3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 11 12 13 14 15 16]


In [54]:
#sort
np.random.seed(101)
arr_rand = np.random.randint(1,10, 20).reshape(4,5)
print(arr_rand)

[[2 7 8 9 5]
 [9 6 1 6 9]
 [2 4 9 4 4]
 [3 9 4 8 1]]


In [55]:
arr_sort = np.sort(arr_rand)
print(arr_sort)

[[2 5 7 8 9]
 [1 6 6 9 9]
 [2 4 4 4 9]
 [1 3 4 8 9]]


In [57]:
print(arr_rand)

[[2 7 8 9 5]
 [9 6 1 6 9]
 [2 4 9 4 4]
 [3 9 4 8 1]]


In [58]:
arr_sort = np.sort(arr_rand, axis = 0)
print(arr_sort)

[[2 4 1 4 1]
 [2 6 4 6 4]
 [3 7 8 8 5]
 [9 9 9 9 9]]


In [59]:
# insert

print(arr_sort)

[[2 4 1 4 1]
 [2 6 4 6 4]
 [3 7 8 8 5]
 [9 9 9 9 9]]


In [65]:
arr_sort = np.arange(1,31).reshape(6,5)

print(arr_sort)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [67]:
arr_ins = np.insert(arr_sort, 1, [0,0,0,0,0,0], axis = 1)

print(arr_ins)

[[ 1  0  2  3  4  5]
 [ 6  0  7  8  9 10]
 [11  0 12 13 14 15]
 [16  0 17 18 19 20]
 [21  0 22 23 24 25]
 [26  0 27 28 29 30]]


In [63]:
print(arr_sort)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [64]:
arr_ins1 = np.insert(arr_ins, 4, [1,1,1,1,1,1], axis = 0)

print(arr_ins1)

[[ 1  0  2  3  4  5]
 [ 6  0  7  8  9 10]
 [11  0 12 13 14 15]
 [16  0 17 18 19 20]
 [ 1  1  1  1  1  1]
 [21  0 22 23 24 25]
 [26  0 27 28 29 30]]


In [ ]:
print(arr_ins)

In [ ]:
arr_ins[0][1] = 20

print(arr_ins)
print(arr_sort)

In [68]:
print(arr_ins)

[[ 1  0  2  3  4  5]
 [ 6  0  7  8  9 10]
 [11  0 12 13 14 15]
 [16  0 17 18 19 20]
 [21  0 22 23 24 25]
 [26  0 27 28 29 30]]


In [69]:
arr_flat = arr_ins.flatten()
print(arr_flat)

[ 1  0  2  3  4  5  6  0  7  8  9 10 11  0 12 13 14 15 16  0 17 18 19 20
 21  0 22 23 24 25 26  0 27 28 29 30]


In [70]:
arr_flat_ins = np.insert(arr_flat, 4, 20)

print(arr_flat_ins)

[ 1  0  2  3 20  4  5  6  0  7  8  9 10 11  0 12 13 14 15 16  0 17 18 19
 20 21  0 22 23 24 25 26  0 27 28 29 30]


In [ ]:
#Transpose

In [71]:
arr_1 = np.arange(1,25).reshape(4,6)

arr_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [72]:
arr_2 = arr_1.transpose() #Returns only a view of the transposed array and does not have a inplace parameter - so to see
# the effect - must save the transposed view to a variable.

arr_2

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [73]:
arr_2[2][3] = 777

arr_2

array([[  1,   7,  13,  19],
       [  2,   8,  14,  20],
       [  3,   9,  15, 777],
       [  4,  10,  16,  22],
       [  5,  11,  17,  23],
       [  6,  12,  18,  24]])

In [74]:
arr_1

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20, 777,  22,  23,  24]])

In [75]:
import copy

arr_3 = copy.deepcopy(arr_1.transpose())

In [76]:
arr_3

array([[  1,   7,  13,  19],
       [  2,   8,  14,  20],
       [  3,   9,  15, 777],
       [  4,  10,  16,  22],
       [  5,  11,  17,  23],
       [  6,  12,  18,  24]])

In [77]:
arr_3[0][0] = 1000

arr_3

array([[1000,    7,   13,   19],
       [   2,    8,   14,   20],
       [   3,    9,   15,  777],
       [   4,   10,   16,   22],
       [   5,   11,   17,   23],
       [   6,   12,   18,   24]])

In [78]:
arr_1

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20, 777,  22,  23,  24]])

In [79]:
arr_1 = np.arange(1,25).reshape(2,3,4)

arr_1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [80]:
# 0,1,2

# 2 3 4

# 1,0,2

arr_2 = np.transpose(arr_1, (1,0,2))

print(arr_2)
#arr_2.shape

[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


In [81]:
arr_3 = np.transpose(arr_1, (1,2,0))

print(arr_1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [82]:
print(arr_3)

[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [ ]:
np_arr1 = np.arange(1,21).reshape(4,5)

np_arr2 = np.arange(1,201,10).reshape(5,4)

print(np_arr1)

In [83]:
print(np_arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  11  21  31]
 [ 41  51  61  71]
 [ 81  91 101 111]
 [121 131 141 151]
 [161 171 181 191]]


In [84]:
np.dot(np_arr1,np_arr2)

array([[ 1615,  1765,  1915,  2065],
       [ 3640,  4040,  4440,  4840],
       [ 5665,  6315,  6965,  7615],
       [ 7690,  8590,  9490, 10390]])

In [ ]:
print(dir(np))

In [94]:
import numpy as np

np_date = np.datetime64('today', 'D')+2

print(np_date)


2022-08-22


https://numpy.org/doc/stable/reference/arrays.datetime.html

In [95]:
print(dir(np.datetime64))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_interface__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__copy__', '__deepcopy__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__xor__', 'all', 'any', 'argmax', 'argmin', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjug

In [96]:
import datetime

print(dir(datetime.datetime))

['__add__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', 'astimezone', 'combine', 'ctime', 'date', 'day', 'dst', 'fold', 'fromisocalendar', 'fromisoformat', 'fromordinal', 'fromtimestamp', 'hour', 'isocalendar', 'isoformat', 'isoweekday', 'max', 'microsecond', 'min', 'minute', 'month', 'now', 'replace', 'resolution', 'second', 'strftime', 'strptime', 'time', 'timestamp', 'timetuple', 'timetz', 'today', 'toordinal', 'tzinfo', 'tzname', 'utcfromtimestamp', 'utcnow', 'utcoffset', 'utctimetuple', 'weekday', 'year']


In [ ]:
print(dir(np))